# Generated by Django 4.0.3 on 2022-06-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'publication_category',
                'ordering': ('cat',),
            },
        ),
        migrations.CreateModel(
            name='PublModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.ImageField(blank=True, upload_to='publication_bg_img/', verbose_name='background')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publihed')),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Сategories', to='publication.catmodel', to_field='cat')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Creaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publocation',
                'verbose_name_plural': 'Publocations',
                'db_table': 'publication',
                'ordering': ('created_at',),
            },
        ),
    ]
